version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 128m
    hostname: appointments
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '80:80'
    environment:
      - PORT=$PORT,
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - JWT_SECRET=$JWT_SECRET
      - RMQ_HOST=$RMQ_HOST
      - RMQ_PROTOCOL=$RMQ_PROTOCOL
      - RMQ_PORT=$RMQ_PORT
      - RMQ_USER=$RMQ_USER
      - RMQ_PASSWORD=$RMQ_PASSWORD
