version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: healy
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: appointments
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
