const DIRECT_EXCHANGE_TYPE = 'direct';
const USERS_APPOINTMENTS_EXCHANGE = 'usersAppointments';
const USER_CREATED_EVENT = 'USER_CREATED';

module.exports = {
  USERS_APPOINTMENTS_EXCHANGE,
  USER_CREATED_EVENT,
  DIRECT_EXCHANGE_TYPE,
};
