const DIRECT_EXCHANGE_TYPE = 'direct';
const HEALY_EXCHANGE = 'healy';
const USER_CREATED_EVENT = 'USER_CREATED';
const USER_UPDATED_EVENT = 'USER_UPDATED';
const DOCTOR_CREATED_EVENT = 'DOCTOR_CREATED';
const DOCTOR_CONFIRMED_EVENT = 'DOCTOR_CONFIRMED';
const CHAT_STARTED_EVENT = 'CHAT_STARTED';
const REMINDER_24_HS_EVENT = 'REMINDER_24_HS';
const REMINDER_48_HS_EVENT = 'REMINDER_48_HS';
const APPT_CANCEL_BY_DOCTOR = 'APPT_CANCEL_BY_DOCTOR';
const DAY_CANCEL_BY_DOCTOR = 'DAY_CANCEL_BY_DOCTOR';
const APPTS_QUEUE = 'APPTS';

module.exports = {
  HEALY_EXCHANGE,
  APPTS_QUEUE,
  USER_CREATED_EVENT,
  USER_UPDATED_EVENT,
  DOCTOR_CREATED_EVENT,
  DOCTOR_CONFIRMED_EVENT,
  CHAT_STARTED_EVENT,
  REMINDER_24_HS_EVENT,
  REMINDER_48_HS_EVENT,
  DIRECT_EXCHANGE_TYPE,
  APPT_CANCEL_BY_DOCTOR,
  DAY_CANCEL_BY_DOCTOR,
};
